### ISSUE TITLE
[FEAT] : Makefile to init the project

### ISSUE THREAD

**Issue by prisca-c** [prisca-c/mind-reader#5]
## [FEAT] : Makefile to init the project

Make project initiation more easy.

## Description

Right now to initiate a project we put manually command into terminal (That's not awfull but we love easy to install project 😄 )

What would be cool is to have a Makefile which will init our project so it ready to use !

We want the installation step (check the README) to be run, but we also want database migration + seeder to run.

Don't add `pnpm dev` and `pnpm jobs:run` to Makefile's init .

And don't forget to update the README !

**Comment by Suvendu-UI** [comment]
pls assign me this issue

**Comment by prisca-c** [comment]
Sure ! 😄

**Comment by Suvendu-UI** [comment]
hey @prisca-c  pls review this pr
